/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminEmployersRouteImport } from './routes/admin.employers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as CandidateAnalysisRouteImport } from './routes/candidate.analysis'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as CandidateInternshipsRouteImport } from './routes/candidate.internships'
import { Route as CandidateJobsRouteImport } from './routes/candidate.jobs'
import { Route as CandidateRoadmapRouteImport } from './routes/candidate.roadmap'
import { Route as CandidateSkillGapRouteImport } from './routes/candidate.skill-gap'
import { Route as CandidateUploadRouteImport } from './routes/candidate.upload'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as EmployerCreateJobRouteImport } from './routes/employer.create-job'
import { Route as EmployerJobsRouteImport } from './routes/employer.jobs'
import { Route as EmployerCandidatesIndexRouteImport } from './routes/employer.candidates.index'
import { Route as EmployerCandidatesCandidateIdRouteImport } from './routes/employer.candidates.$candidateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployersRoute = AdminEmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateAnalysisRoute = CandidateAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateInternshipsRoute = CandidateInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateJobsRoute = CandidateJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateRoadmapRoute = CandidateRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateSkillGapRoute = CandidateSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateUploadRoute = CandidateUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => CandidateRoute,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCreateJobRoute = EmployerCreateJobRouteImport.update({
  id: '/create-job',
  path: '/create-job',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCandidatesIndexRoute = EmployerCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCandidatesCandidateIdRoute =
  EmployerCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => EmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/candidate': typeof CandidateRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/analysis': typeof CandidateAnalysisRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/internships': typeof CandidateInternshipsRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/skill-gap': typeof CandidateSkillGapRoute
  '/candidate/upload': typeof CandidateUploadRoute
  '/employer/create-job': typeof EmployerCreateJobRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/employer/candidates/$candidateId': typeof EmployerCandidatesCandidateIdRoute
  '/employer/candidates/': typeof EmployerCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/analysis': typeof CandidateAnalysisRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/internships': typeof CandidateInternshipsRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/skill-gap': typeof CandidateSkillGapRoute
  '/candidate/upload': typeof CandidateUploadRoute
  '/employer/create-job': typeof EmployerCreateJobRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/admin': typeof AdminIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/employer/candidates/$candidateId': typeof EmployerCandidatesCandidateIdRoute
  '/employer/candidates': typeof EmployerCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/candidate': typeof CandidateRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/analysis': typeof CandidateAnalysisRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/internships': typeof CandidateInternshipsRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/skill-gap': typeof CandidateSkillGapRoute
  '/candidate/upload': typeof CandidateUploadRoute
  '/employer/create-job': typeof EmployerCreateJobRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/employer/candidates/$candidateId': typeof EmployerCandidatesCandidateIdRoute
  '/employer/candidates/': typeof EmployerCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/candidate'
    | '/employer'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/candidates'
    | '/admin/employers'
    | '/admin/reports'
    | '/admin/users'
    | '/candidate/analysis'
    | '/candidate/applications'
    | '/candidate/internships'
    | '/candidate/jobs'
    | '/candidate/roadmap'
    | '/candidate/skill-gap'
    | '/candidate/upload'
    | '/employer/create-job'
    | '/employer/jobs'
    | '/admin/'
    | '/candidate/'
    | '/employer/'
    | '/employer/candidates/$candidateId'
    | '/employer/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/candidates'
    | '/admin/employers'
    | '/admin/reports'
    | '/admin/users'
    | '/candidate/analysis'
    | '/candidate/applications'
    | '/candidate/internships'
    | '/candidate/jobs'
    | '/candidate/roadmap'
    | '/candidate/skill-gap'
    | '/candidate/upload'
    | '/employer/create-job'
    | '/employer/jobs'
    | '/admin'
    | '/candidate'
    | '/employer'
    | '/employer/candidates/$candidateId'
    | '/employer/candidates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/candidate'
    | '/employer'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/candidates'
    | '/admin/employers'
    | '/admin/reports'
    | '/admin/users'
    | '/candidate/analysis'
    | '/candidate/applications'
    | '/candidate/internships'
    | '/candidate/jobs'
    | '/candidate/roadmap'
    | '/candidate/skill-gap'
    | '/candidate/upload'
    | '/employer/create-job'
    | '/employer/jobs'
    | '/admin/'
    | '/candidate/'
    | '/employer/'
    | '/employer/candidates/$candidateId'
    | '/employer/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CandidateRoute: typeof CandidateRouteWithChildren
  EmployerRoute: typeof EmployerRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employers': {
      id: '/admin/employers'
      path: '/employers'
      fullPath: '/admin/employers'
      preLoaderRoute: typeof AdminEmployersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/analysis': {
      id: '/candidate/analysis'
      path: '/analysis'
      fullPath: '/candidate/analysis'
      preLoaderRoute: typeof CandidateAnalysisRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/internships': {
      id: '/candidate/internships'
      path: '/internships'
      fullPath: '/candidate/internships'
      preLoaderRoute: typeof CandidateInternshipsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/jobs': {
      id: '/candidate/jobs'
      path: '/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof CandidateJobsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/roadmap': {
      id: '/candidate/roadmap'
      path: '/roadmap'
      fullPath: '/candidate/roadmap'
      preLoaderRoute: typeof CandidateRoadmapRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/skill-gap': {
      id: '/candidate/skill-gap'
      path: '/skill-gap'
      fullPath: '/candidate/skill-gap'
      preLoaderRoute: typeof CandidateSkillGapRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/upload': {
      id: '/candidate/upload'
      path: '/upload'
      fullPath: '/candidate/upload'
      preLoaderRoute: typeof CandidateUploadRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/create-job': {
      id: '/employer/create-job'
      path: '/create-job'
      fullPath: '/employer/create-job'
      preLoaderRoute: typeof EmployerCreateJobRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs': {
      id: '/employer/jobs'
      path: '/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/candidates/': {
      id: '/employer/candidates/'
      path: '/candidates'
      fullPath: '/employer/candidates/'
      preLoaderRoute: typeof EmployerCandidatesIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/candidates/$candidateId': {
      id: '/employer/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/employer/candidates/$candidateId'
      preLoaderRoute: typeof EmployerCandidatesCandidateIdRouteImport
      parentRoute: typeof EmployerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminEmployersRoute: typeof AdminEmployersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminEmployersRoute: AdminEmployersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CandidateRouteChildren {
  CandidateAnalysisRoute: typeof CandidateAnalysisRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateInternshipsRoute: typeof CandidateInternshipsRoute
  CandidateJobsRoute: typeof CandidateJobsRoute
  CandidateRoadmapRoute: typeof CandidateRoadmapRoute
  CandidateSkillGapRoute: typeof CandidateSkillGapRoute
  CandidateUploadRoute: typeof CandidateUploadRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateAnalysisRoute: CandidateAnalysisRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateInternshipsRoute: CandidateInternshipsRoute,
  CandidateJobsRoute: CandidateJobsRoute,
  CandidateRoadmapRoute: CandidateRoadmapRoute,
  CandidateSkillGapRoute: CandidateSkillGapRoute,
  CandidateUploadRoute: CandidateUploadRoute,
  CandidateIndexRoute: CandidateIndexRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface EmployerRouteChildren {
  EmployerCreateJobRoute: typeof EmployerCreateJobRoute
  EmployerJobsRoute: typeof EmployerJobsRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  EmployerCandidatesCandidateIdRoute: typeof EmployerCandidatesCandidateIdRoute
  EmployerCandidatesIndexRoute: typeof EmployerCandidatesIndexRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerCreateJobRoute: EmployerCreateJobRoute,
  EmployerJobsRoute: EmployerJobsRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  EmployerCandidatesCandidateIdRoute: EmployerCandidatesCandidateIdRoute,
  EmployerCandidatesIndexRoute: EmployerCandidatesIndexRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CandidateRoute: CandidateRouteWithChildren,
  EmployerRoute: EmployerRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
